generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           DisciplinarySanctionType
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          disciplinary_sanction_type
    with_propel_route:     1

    config:
      actions: ~
      fields:
      list:
        display:           [name]
        object_actions:
          _edit:
            credentials:   [edit_disciplinary_sanction_type]
          _delete:
            credentials:   [new_disciplinary_sanction_type]
            condition:     canBeDeleted
        batch_actions:     []
        actions:
          _new:
            label: Nuevo motivo de sanci√≥n
            credentials:   [new_disciplinary_sanction_type]
      filter:
        class: false
      form:   ~
      edit:   ~
      new:    ~
