generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           ExaminationSubject
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          examination_subject
    with_propel_route:     1

    config:
      actions: ~
      fields:
        examination_subject_teacher_list:
          label: Teachers
      list:
        title: Listado de materias de la mesa de ex치men
        layout: stacked
        params: |
          %%_information%%
        display: [Subjects]
        batch_actions: []
        object_actions:
          _edit:
            credentials: [edit_examination_subject]
          manage_students:
            action: manageStudents
            condition: canManageStudents
            credentials: [edit_examination_subject_califications]
          students:
            action: students
            credentials: [edit_examination_subject_califications]
          califications:
            action: califications
            credentials: [[edit_examination_subject_califications, edit_closed_examination]]
          close:
            action: close
            label: Close examination
            condition: canBeClosed
            credentials: [edit_examination_subject]
          changelog:
            action:         changelogMarks
            label:          Auditoria de notas
            credentials:    [edit_examination]
          print_students:
            label: Print students
            action: printStudents
            credentials: [edit_examination]
          _delete:
            condition: canDelete
            credentials: [edit_examination]
          assign_physical_sheet:
            action: assignPhysicalSheet
            condition: canAssignPhysicalSheet
            credentials: [assign_physical_sheet]
          generate_record:
            action: generateRecord
            condition: canGenerateRecord
            credentials: [generate_record]
            params:         confirm='Est치 seguro? Si el acta ya se encuentra generada se perder치n los datos generados anteriormente.'
          print_record:
            action: printRecord
            condition: canPrintRecord
            credentials: [print_record]
        actions:
          back:
            action: back
            label:  Volver
      filter:
      form:
        actions:
          _list:
            label: Back
          _save:
      edit:
        title: Editar materia de la mesa de ex치men
        actions:
          _list:
            label:        Volver al listado
          _save_and_list:
            label:        Guardar materia
      new:     ~
