generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           Tutor
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tutor
    with_propel_route:     1

    config:
      actions:
      exportation:
        enabled: true
        title: Tutor List
        type: xls
        fieldSelection:
          lastname:
            label: Lastname
            method: getPersonLastname
            decorator: text
          person_firstname:
            label: Firstname
            method: getPersonFirstname
            decorator: text
          person_full_identification:
            label: Identification number
            method: getPersonFullIdentification
            decorator: text
          tutor_type:
            label: Tutor type
            method: getTutorType
            decorator: text
          in_charge_of:
            label: In charge of
            method: getStudentTutorsString
            decorator: text
          person_phone:
            label: Phone
            method: getPersonPhone
            decorator: text
          person_alternative_phone:
            label: Alternative phone
            method: getPersonAlternativePhone
            decorator: text
          person_email:
            label: Email
            method: getPersonEmail
            decorator: text
          person_address:
            label: Address
            method: getPersonAddress
            decorator: text
          occupation:
            label: Occupation
            method: getOccupation
            decorator: text
          occupation_category:
            label: Occupation category id
            method: getOccupationCategory
            decorator: text
          study:
            label: Study id
            method: getStudy
            decorator: text
      fields:
        #necesario para que no se cuelgue el list
        person:
        person_lastname:                  { label: Lastname, column_name: PersonPeer::LASTNAME }
        person_firstname:                 { label: Firstname, column_name: PersonPeer::FIRSTNAME }
        person_full_identification:       { label: Identification number, column_name: PersonPeer::IDENTIFICATION_NUMBER }
        person_sf_guard_user:             { label: Username }
        student_tutor:  { label: In charge of }

      list:
        title:             Listado de tutores
        peer_method:       doSelectJoinAll
        display:           [ person_lastname, person_firstname, person_full_identification, _is_alive, person_phone, _student_tutor ]
        sort: [ person_lastname ]
        batch_actions:     []
        actions:
          _new:
            label:         Nuevo tutor
            credentials:   [edit_tutor]
          _user_export:
        object_actions:
          _show:
            credentials:   [show_tutor]
          _edit:
            credentials:   [edit_tutor]
          _delete:
            credentials:   [edit_tutor]
          aggregate_preceptor:
            label:  Aggregate as a preceptor
            action: aggregateAsPreceptor
            condition:  canAddPreceptor
            credentials:  [edit_tutor]   
          aggregate_profesor:
            label:  Aggregate as a teacher
            action: aggregateAsTeacher
            condition:  canAddTeacher
            credentials:  [edit_tutor] 
          generate_user:
            credentials:   [edit_tutor]
            condition: canGenerateUser
            action: generateUser
          deactivate:
            label: Set inactive
            credentials: [edit_tutor]
            action: deactivate
            condition: canBeDeactivated
          activate:
            label: Set active
            credentials: [edit_tutor]
            action: activate
            condition: canBeActivated
 
      filter:
      form:
      edit:
        actions:
          _list:
            label:            Volver al listado
          _save_and_list:
            label:            Guardar tutor
      new:
        actions:
          _list:
            label:            Volver al listado
          _save_and_list:
            label:            Guardar tutor
          _save_and_add:
            label:            Guardar y agregar otro tutor
      show:
        title:              Detalles del tutor "%%person%%"
        display:
          'Personal data': [ _person ]
          'Contact data':  [ _address ]
          'In charge of':  [ _students ]
        actions:
          _list:
            label:            Volver al listado
