generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           Course
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          commission
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        title:              Listado de comisiones
        display:            [name]
        layout:             stacked
        params:             |
          %%_commission_info%%
        actions:
          _new:
            credentials:    [new_course]
            label:          Nueva comisión
        batch_actions: []
        object_actions:

          _edit:
            condition:      canBeEdited
            credentials:    [edit_course]

          add_subject:
            action:         addSubject
            credentials:    [edit_course]

          configuration:
            label:          Configuration course
            action:         courseConfiguration
            credentials:    [course_configuration]
            condition:      canConfigurate

          copy_students_from_other_course:
            action:         copyStudentsFromOtherCourse
            credentials:    [edit_course]
            condition:      canCopyStudentsFromOtherCourse
            label:          Copiar alumnos de otra comisión

          manage_students:
            action:         courseSubjectStudent
            credentials:    [edit_course]
            condition:      canCourseSubjectStudent

          preceptors:
            action:         preceptors
            condition:      canPreceptors
            credentials:    [edit_course_preceptors]

          teachers:
            action:         courseTeachers
            condition:      canTeachers
            credentials:    [edit_course]

          related_to_a_division:
            action:         relatedToDivision
            credentials:    [edit_course]
            condition:      canRelatedToDivision

          manage_course_days:
            action:         manageCourseDays
            label:          Manage commission days
            condition:      canManageCourseDays
            credentials:    [edit_course_day]

          students:
            label:          Listado de alumnos
            action:         students
            condition:      canListStudents
            credentials:    [show_course]

          calificateNonNumericalMark:
            label:          Calificate non numerical mark
            action:         calificateNonNumericalMark
            credentials:    [edit_division_course_califications]
            condition:      canCalificate

          califications:
            action:         califications
            credentials:    [edit_division_course_califications]
            condition:      canEditMarks

          changelog:
            action:         changelogMarks
            label:          Auditoria de notas
            credentials:    [edit_course]

          close:
            label:          Close period
            action:         close
            credentials:    [close_course_period]
            condition:      canBeClosed

          printCalification:
            label:          Print califications
            action:         printCalification
            credentials:    [show_division_course_califications]

          revert_period:
            label:          Back to period
            action:         backPeriod
            credentials:    [back_period_course]
            condition:      canBackPeriodCommission
            params:         confirm='Are you sure?'

          attendanceSubject:
            label:          Load Attendances
            action:         attendanceSubject
            condition:      hasAttendanceForSubject

          seeAttendanceSheet:
            label:          Show attendance sheet
            action:         attendanceSheetByCourseSubject
            credentials:    [show_course]
            condition:      canSeeAttendanceSheet
            
          revertCalificateNonNumericalMark:
            label:          Revert calificate non numerical mark
            action:         revertCalificateNonNumericalMark
            credentials:    [edit_division_course_califications]
            condition:      canRevertCalificate

          _delete:
            condition:      canBeDeleted
            credentials:    [edit_course]
          
          assign_physical_sheet:
            action: assignPhysicalSheet
            condition: canAssignPhysicalSheet
            credentials: [assign_physical_sheet]
            
          generate_record:
            action: generateRecord
            condition: canGenerateRecord
            credentials: [generate_record]

      filter:
      form:    ~
      edit:
        actions:
          _list:
            label:        Volver al listado
          _save_and_list:
            label:        Guardar comisión
      new:
        actions:
          _list:
            label:        Volver al listado
          _save_and_list:
            label:        Guardar comisión
          _save_and_add:
            label:        Guardar y agregar otra comisión
