generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           CareerSchoolYear
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          career_school_year
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        title:      Carreras del año lectivo
        display:    [career]
        object_actions:


          close:
            action:       close
            condition:    canClose
            label:        Close courses
            credentials:  [edit_school_year]
            params:
              onclick= blockScreen();

          configuration:
            action:         configuration
            label:          Configuración
            credentials:    [edit_school_year]
            condition:      canBeEdited

          showConfiguration:
            action:         showConfiguration
            label:          Configuración
            credentials:    [edit_school_year]
            condition:      canShowConfiguration

          copy_configuration:
            action:         copyConfiguration
            label:          Copy last year configuration
            credentials:    [edit_school_year]
            condition:      canCopyConfiguration

          matriculate_students_from_last_year:
            action:         matriculateLastYearStudents
            label:          matriculate last year students
            credentials:    [edit_school_year]
            condition:      canMatriculateStudentsFromLastYear

          create_last_year_divisions:
            action:         createLastYearDivisions
            label:          Create the same last year divisions
            credentials:    [edit_school_year]
            condition:      canCreateLastYearDivisions

          matriculate_graduated_from_other_career:
            action:         matriculateGraduatedFromOtherCareer
            label:          Matriculate graduated from other career
            credentials:    [edit_school_year]
            condition:      canMatriculateGraduatedFromOtherCareer

          subjects:
            action:         careerCareerSubjectSchoolYear
            label:          Materias
            credentials:    [edit_school_year]

          optionals:
            action:         optionals
            label:          Optativas
            credentials:    [edit_school_year]

          career_view:
            action:         careerView
            label:          Plan de estudios
            credentials:    [show_school_year]

          periods:
            action:         period
            label:          Periodos
            credentials:    [edit_school_year]

          _delete:
            condition:      canBeDeleted
            credentials:    [edit_school_year]


        batch_actions:  []
        actions:        []
      filter:
        class:  -
      form:    ~
      edit:    ~
      new:     ~
