generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           Pathway
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          pathway
    with_propel_route:     1

    config:
      actions: ~
      fields:
        school_year:  { label: Año lectivo que se recupera }
      list:
        title:             Pathway list
        sort:              [name, asc]
        display:           [name, school_year]
        batch_actions:     []
        actions:
          _new:
            credentials: [edit_pathway]
        object_actions:
          _edit:
          _show:
          _delete:
            condition: canBeDeleted
      filter:
        class: false
      form:    ~
      edit:
        title:             Edición de "%%name%%"
        display:           [name, school_year_id]
        actions:
          _list:
            label:        Volver al listado de trayectorias
          _save_and_list:
      new:
        title:             Crear una nueva trayectoria
        display:           [name, school_year_id]
        actions:
          _list:
            label:        Volver al listado de trayectorias
          _save_and_list:
      show:
          title: Ver "%%name%%"
          display: [school_year, _student_list]
          actions:
            _list:
              label:        Volver al listado de trayectorias
