all:
  version:
    number: <?php echo file_get_contents(sfConfig::get('sf_root_dir').'/VERSION');?>

  testing: false
  career:
    max_quantity_years: 10
  revisited_generator:
    show_disabled_actions: true

  close_course_subject_schol_year_max_error: 50

  mailer:
    from: no-responder@desarrollo.unlp.edu.ar
    name_from: Kimkëlen
    new_user_subject: Nuevo usuario de Kimkëlen