generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           Division
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          division
    with_propel_route:     1

    config:
      actions: ~
      fields:
        id:
          label:  División
        division_courses:
          label: Crear materias
      list:
        title:              Listado de divisiones
        display:            [id]
        layout:             stacked
        params:             |
          <div class='info_div'><strong>%%name%%</strong>
          <div class='info_div'><em><strong>Año lectivo:</strong> %%school_year%% </em></div>
          <div class='info_div'><em><strong>Carrera:</strong> %%career_school_year%%</em></div>
          <div class='info_div'>%%_division_info%%</div>
        actions:
          _new:
            credentials: [new_division]
            label: Nueva división
          _user_export:
        batch_actions: []
        object_actions:

          _show:
            credentials: [show_course]

          division_students:
            action: divisionStudents
            label:  Administrar alumnos
            condition: canDivisionStudents
            credentials:  [edit_course]

          division_preceptors:
            action: divisionPreceptors
            label:  Preceptors
            condition: canDivisionPreceptors
            credentials:  [edit_division_preceptors]

          show_calendar:
            action: showCalendar
            credentials:   [show_course]

          students:
            label:          Listado de alumnos
            action:         students
            condition:      canListStudents
            credentials:    [show_course]

          division_courses:
            action: divisionCourses
            credentials: [show_course]

          printCalification:
            label:   Print califications
            action:  printCalification
            credentials:    [show_division_califications]
            condition: canPrintCalification

          boletines:
            action: printReportCard
            label:  Imprimir boletines division
            credentials:  [print_report_card]
            condition: canPrintReportCards

          student_conduct:
            action: studentConduct
            label: Student conduct
            condition: canManageConduct
            credentials: [edit_division_preceptors]

          show_disciplinary_sanction_report:
            label: Student disciplinary sanction report
            action: showDisciplinarySanctionReport
            credentials: [show_disciplinary_sanction]

          division_configure:
            label:  Configuración de cantidad de inasistencias permitidas
            action: courseConfiguration
            credentials:  [course_configuration]

          attendanceDay:
            label: Load Attendances
            action: attendanceDay
            credentials:  [edit_absence_per_day]
            condition: canLoadAttendances

          seeAttendanceSheet:
            label:   Show attendance sheet
            action:  attendanceSheetByDay
            credentials:    [[show_absence_per_day,show_absence_per_subject]]
            condition: canManageAttendance

          show_assistance_report:
            label: Student assistance report
            action: showAssistanceReport
            credentials: [[show_absence_per_day,show_absence_per_subject]]

          _delete:
            credentials: [delete_division]
            condition: canBeDeleted
            
          show_course_result_report:
            label:   Course result report
            action:  showCourseResultReport
            credentials:    [show_division_course_califications]
            condition: canShowCourseResultReport
            
      filter:
        class:  ~
      form:
      edit:
        title: Editar división
        actions:
          _list:
            label:        Volver al listado
          _save_and_list:
            label:        Guardar división
      new:
        title: Nueva división
        actions:
          _list:
            label:        Volver al listado
          _save_and_list:
            label:        Guardar división
          _save_and_add:
            label:        Guardar y agregar otra división
      show:
        title: Detalles de la división
        display: [_division_show_tabs]
        actions:
          _list:
            label: Volver al listado
          division_students:
            action: divisionStudents
            label:  Administrar alumnos
            credentials:  [edit_course]
          show_calendar:
            action: showCalendar
            credentials:   [show_course]
          division_preceptors:
            action: divisionPreceptors
            label:  Preceptors
            credentials:  [edit_division_preceptors]
          division_courses:
            action: divisionCourses
            label:  Materias
            credentials: [show_course]
          _delete:
            credentials: [delete_division]
            condition: canBeDeleted
      exportation:
        enabled: true
        title: Divisiones
        type: xls
        fieldSelection:
          title:
            label: Título de división
            method: getDivisionTitle
            decorator: text
          career:
            label: Career
            method: getCareer
            decorator: text
          count_students:
            label: Count students
            method: countStudents
            decorator: text
