generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           StudentExaminationRepprovedSubject
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          student_examination_repproved_subject
    with_propel_route:     1


    config:
      actions: ~
      exportation:
        enabled: true
        title: Student list
        type: xls
        fieldSelection:
          student:
            label: Student
            method: getStudent
            decorator: text

      list:
        title:  Alumnos
        display:  [student]  
        max_per_page: 50
        batch_actions: []
        object_actions: []
        actions:
          back:
            label: Volver al listado de mesas
            action: back
          _user_export:
        peer_method: doSelect
        
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
