generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           StudentDisciplinarySanction
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sanction
    with_propel_route:     1

    config:
      exportation:
        enabled: true
        title: Lista de Sanciones
        type: xls
        fieldSelection:
          student:
            decorator: text
            method: getStudent
            label: Estudiante
          request_date:
            decorator: date
            method: getRequestDate
            label: Fecha de Solicitud
          resolution_date:
            decorator: text
            method: getResolutionDate
            label: Fecha de Resolución
          school_year:
            decorator: text
            method: getSchoolYear
            label: Año Lectivo
          responsible:
            decorator: text
            method: getResponsible
            label: Responsable
          applicant:
            decorator: text
            method: getApplicant
            label: Solicitante
          sanction_type:
            decorator: text
            method: getSanctionType
            label: Tipo
          disciplinary_sanction_type:
            decorator: text
            method: getDisciplinarySanctionType
            label: Tipo de Sanción
          value:
            decorator: text
            method: getValue
            label: Valor


      actions: ~
      fields:
        request_date:
          date_format: 'dd/MM/yyyy'
        resolution_date:
          date_format: 'dd/MM/yyyy'
        sanction_type:
          label: Tipo
        sanction_type_id:
          label: Tipo
        responsible:
          label: Responsable
        responsible_id:
          label: Responsable
        applicant_id:
          label: Solicitante
        value:
          label: Valor
        disciplinary_sanction_type_id:
          label: Tipo de Sanción Disciplinaria

      list:
        title: Consulta de Sanciones Disciplinarias
        display: [ student, request_date, school_year, applicant, responsible, sanction_type, disciplinary_sanction_type ]
        batch_actions: []
        actions:
          _export: ~
        object_actions:
          _show: ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
      show:
        title: Detalles de Sanción Disciplinaria
        display: [ number, student, request_date, resolution_date, school_year, applicant, responsible, sanction_type, disciplinary_sanction_type, value, observation, _document_show ]
        actions:
          _list:
            label: Volver al Listado
