generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           Orientation
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          orientation
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        title:              Orientations
        batch_actions:      []
        display:            [name]
        object_actions:
          _edit:
            credentials: [edit_orientation]
          sub_orientations:
            label: Sub orientations
            credentials: [edit_sub_orientation]
            action: SubOrientations
          _delete:
            credentials: [edit_orientation]
            condition:    canBeDeleted
        actions:
          _new:
            label: New orientation
            credentials: [edit_orientation]

      filter:
        class:              false
      form:    ~
      edit:
        title: Edit orientation
        actions:
          _list:
            label:          Volver al listado
          _save_and_list:
            label:          Save orientation
      new:
        title: New orientation
        actions:
          _list:
            label:          Volver al listado
          _save_and_list:
            label:          Save orientation
          _save_and_add:
            label:          Save and add orientation