generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           Personal
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          student_office
    with_propel_route:     1

    config:
      actions: ~
      
      fields:
        #necesario para que no se cuelque el list
        person:
        person_lastname:                    { label: Lastname, column_name: PersonPeer::LASTNAME }
        person_firstname:                   { label: Firstname, column_name: PersonPeer::FIRSTNAME }
        person_full_identification:       { label: Identification number, column_name: PersonPeer::IDENTIFICATION_NUMBER }
        person_sf_guard_user:             { label: Username}
        person_is_active:    { label: Activo, type: Boolean }
#        aging_institution:            {label:  Fecha de inicio en la instituci√≥n}
#        salary:                       {label:  Salario}


      list:
        title:             Personal de la oficina de alumnos
        peer_method:       doSelectJoinAll
        display:           [ person_lastname, person_firstname, person_full_identification, person_is_active, person_sf_guard_user ]
        sort: [ person_lastname ]
        batch_actions:     []

        object_actions:
          _show:
            credentials:   [show_student_office]
          _edit:
            credentials:   [edit_student_office]
          _delete:
            credentials:   [edit_student_office]

          activate:
            label: Set active
            credentials: [edit_personal]
            action: personActivation
            condition: canPersonBeActivated

          deactivate:
            label: Set inactive
            credentials: [edit_personal]
            action: personActivation
            condition: canPersonBeDeactivated
            

        actions:
          _new:
            label:         Nuevo personal de la oficina de alumnos
            credentials:   [edit_personal]

      filter:
        class:             false
      form:    ~
      edit:
        actions:
          _list:
            label:         Volver al listado
          _save_and_list:
            label:         Guardar personal
      new:
        actions:
          _list:
            label:         Volver al listado
          _save_and_list:
            label:         Guardar personal
          _save_and_add:
            label:         Guardar y agregar otro personal
      show:
        title: Detalles del personal de la oficina de alumnos
        actions:
          _list:
            label:         Volver al listado
