generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           Student
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          student
    with_propel_route:     1

    config:
      actions:
      exportation:
        enabled: true
        title: Student list
        type: xls
        fieldSelection:
          global_file_number:
            label: Global file number
            method: getGlobalFileNumber
            decorator: text
          lastname:
            label: Lastname
            method: getPersonLastname
            decorator: text
          person_firstname:
            label: Firstname
            method: getPersonFirstname
            decorator: text
          person_identification_type:
            label: Identification type
            method: getPersonIdentificationTypeString
            decorator: text
          person_identification_number:
            label: Identification number
            method: getPersonIdentificationNumber
            decorator: text
          person_birth_date:
            label: Birthdate
            method: getPersonFormattedBirthDate
            decorator: text
          person_email:
            label: Email
            method: getPersonEmail
            decorator: text
          person_phone:
            label: Phone
            method: getPersonPhone
            decorator: text
          person_address:
            label: Address
            method: getPersonAddress
            decorator: text
          person_cuil:
            label: CUIL
            method: getPersonCuil
          person_health_coverage:
            label: Health coverage
            method: getHealthCoverage
            decorator: text
          person_emergency_information:
            label: Emergency information
            method: getEmergencyInformation
            decorator: text
          person_is_active:
            label: Is Active?
            method: getPersonIsActiveString
            decorator: text
          is_registered:
            label: School year registered?
            method: getIsRegisteredString
            decorator: text
          division:
            label:  División/es
            method: getCurrentDivisionsString
            decorator:  text
          current_year:
            label:  Año de cursada
            method: getCurrentCourseYear
            decorator:  integer
          repetitive_curse_subject:
            label:  Materias que desaprobó
            method: getStudentDisapprovedCourseSubjectString
            decorator:  text
          speciality:
            label:  Especialidad
            method: getStudentSpecialityString
            decorator:  text
          orientation:
            label:  Orientación
            method: getStudentOrientationString
            decorator:  text
          health_info:
            label: Health info
            method: getHealthInfoString
            decorator: text
          graduation_school_year_id:
            label: Año de egreso
            method: getGraduationSchoolYear
          origin_school_id:
            label: Escuela de procedencia
            method: getOriginSchool
          tutors:
            label: Tutores
            method: getStudentTutorsString
          tutors_email:
            label: Email de tutores
            method: getStudentTutorsEmailString
          
      fields:
        person:
        person_lastname:  { label: Lastname, column_name: PersonPeer::LASTNAME }
        person_firstname: { label: Firstname, column_name: PersonPeer::FIRSTNAME }
        careers:          { label: Careers}
        person_is_active:    { label: Is Active?, type: Boolean }
        is_registered:    { label: School year registered? }
        person_full_identification:       { label: Identification number, column_name: PersonPeer::IDENTIFICATION_NUMBER }
        person_sf_guard_user:             { label: Username }

      list:
        title:              Student list
        peer_method:        doSelectJoinPerson
        actions:
          _new:
            credentials: [edit_student]
            label:        Nuevo alumno
#          _export:
          _user_export:
        batch_actions:
          registerForCareer:
            label: Career inscriptions
            credentials: [edit_student]
          registerForCurrentSchoolYear:
            label: Administrar matrícula
            credentials: [edit_student]
          _delete:
            credentials: [edit_student]
          manageAllowedSubject:
            label: Materias a cursar
            credentials: [edit_student]
        display: [person_lastname, person_firstname, person_full_identification, person_is_active, person_sf_guard_user, _is_registered, _careers]
        layout: stacked
        params: |
          %%_student_info%%
        sort: [ person_lastname ]
        object_actions:
          _show:
            credentials: [show_student]
            label: Ver Legajo Completo

          _edit:
            credentials: [edit_student]

          _delete:
            credentials: [edit_student]
            condition: canBeDeleted

          regiter_for_careers:
            label: Career register
            credentials: [edit_student]
            action: registerForCareer

          register_for_current_school_year:
            label: School year register
            credentials: [edit_student]
            action: registerForCurrentSchoolYear

          manage_orientation:
            label:  Cambiar orientación
            credentials:  [edit_student]
            action: changeOrientation
            condition:  isInscriptedInCareer

          manage_allowed_subjects:
            label: Subjects to be coursed
            credentials: [ edit_student ]
            condition: canBeManagedForCareerSubjectAllowed
            action: manageCareerSubjectAllowed

          analytical:
            credentials:  [print_report_card]
            action: analytical
            condition: canBeManagedForCareerSubjectAllowed

          activate:
            label: Set active
            credentials: [edit_student]
            action: personActivation
            condition: canPersonBeActivated

          deactivate:
            label: Set inactive
            credentials: [edit_student]
            action: deactivate
            condition: canBeDeactivated

          sanctions:
            credentials: [show_student_disciplinary_sanction]
            label: Sanctions
            action: sanctions

          free:
            credentials: [set_free]
            label: Student free
            action: free
            condition: canBeFree

          print_report_card:
            label:  print report card
            action: printReportCard
            condition: canPrintReportCard
            credentials: [print_report_card]

          student_reincorporation:
            credentials: [student_reincorporation_student]
            label: Student reincorporation
            action: reincorporation
            condition: canBeReincorporated

          student_assistance_sanction_report:
            label: Student assistance and sanction report
            action: showAssistanceAndSanctionReport
            condition: canGenerateReport
            credentials: [show_assistance_sanction_report]
            
          change_student_status:
            label: Change student status
            credentials: [edit_student]
            action: changeStudentStatus
            condition: canChangeStudentStatus
          
          graduate_certificate:
            label: Graduate certificate
            action: printGraduateCertificate
            condition: canPrintGraduateCertificate
            credentials: [[print_certificate, print_graduate_certificate]]
         
          regular_certificate:
            label: Regular certificate
            action: printRegularCertificate
            condition: canPrintRegularCertificate
            credentials: [[print_certificate, print_regular_certificate]]
            
          withdrawn_certificate:
            label: Withdrawn certificate
            action: printWithdrawnCertificate
            condition: canPrintWithdrawnCertificate
            credentials: [[print_certificate, print_withdrawn_certificate]]
            
          free_certificate:
            label: Withdrawn certificate
            action: printFreeCertificate
            condition: canPrintFreeCertificate
            credentials: [[print_certificate, print_free_certificate]]
            
          medical_certificate:
            label: Medical certificates
            action: medicalCertificates
            condition: canManageMerdicalCertificate
            credentials: [show_medical_certificate]
            
      filter:
      form:    ~
      edit:
        title: Editar al alumno "%%person%%"
        actions:
          _list:
            label:              Volver al listado
          _save_and_list:
            label:              Guardar alumno
      new:
        title: Nuevo Alumno
        actions:
          _list:
            label:              Volver al listado
          _save_and_list:
            label:              Guardar alumno
          _save_and_add:
            label:              Guardar y agregar otro alumno
      show:
        title: Detalles del alumno "%%person%%"
        display:
          Alumno:      [_student_show_tabs]
          #Datos postales:        [_address]
          #Datos de salud:        [_health]
          #Historia academica:       [_career_student_histories]
        actions:
          _list:
            label: Volver al listado
          _edit:
            credentials: [edit_student]
          _delete:
            credentials: [edit_student]
            condition: canBeDeleted
          regiter_for_careers:
            label: Career register
            credentials: [edit_student]
            action: registerForCareer
          register_for_current_school_year:
            label: School year register
            credentials: [edit_student]
            action: registerForCurrentSchoolYear
            credentials: [edit_student]
          manage_orientation:
            label:  Cambiar orientacion
            credentials:  [edit_student]
            action: changeOrientation
            condition:  isInscriptedInCareer
          manage_allowed_subjects:
            label: Subjects to be coursed
            credentials: [ edit_student ]
            condition: canBeManagedForCareerSubjectAllowed
            action: manageCareerSubjectAllowed
          equivalence:
            credentials:  [show_equivalence]
            condition:     canManageEquivalence
            action: equivalence
          print_report_card:
            label:  print report card
            action: printReportCard
            condition: canPrintReportCard
            credentials: [print_report_card]
          brothers:
            credentials: [edit_student]
            action: manageBrothers
          tutors:
            credentials: [edit_student]
            action: tutors
          sanctions:
            credentials: [show_student_disciplinary_sanction]
            label: Sanctions
            action: sanctions
          free:
            credentials: [set_free]
            label: Student free
            action: free
            condition: canBeFree
          student_reincorporation:
            credentials: [student_reincorporation_student]
            label: Student reincorporation
            action: reincorporation
            condition: canBeReincorporated
          print_entry_form:
            label: Print entry form
            action: printEntryForm
            credentials: [edit_student]